# Generated by Django 5.0.1 on 2024-02-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_alter_category_options'),
        ('rango', '0006_alter_page_url'),
    ]

    operations = [
    ]
